sudo: enabled

language: node_js

services:
  - docker

before_install:
  - docker build -t davidbaldie/infrastructure .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push